#!/usr/bin/perl -w

# $UNIVERSAL::debug = 1;

use Guardian;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "Guardian",
   ReceiveHandler => \&Receive);
$UNIVERSAL::guardian = Guardian->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::guardian->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::guardian->Execute();
